### ISSUE TITLE
Spot.js throwing errors (out-of-bounds and undefined variables)

### ISSUE THREAD

**Issue by TheEyeOfBrows** [CodingTrain/AStar#18]
Looks like the last two merges were incompatible with each other ( #10 and #12 ).

Spot.js is throwing errors when gathering neighbor information (both regular neighbors and wall neighbors). Part of it looks like it's trying to use indexes outside of the grid range.

**Comment by ootsby** [comment]
Addressed in pr #19. (I was expecting the reference in the pull request to auto link it to this somehow. Disappointing that it didn't.)

**Comment by TheEyeOfBrows** [comment]
Fix looks good! 

Closing the issue.
